# 1.1 Python Introduction to Data Structure

Introduction to Python's features that are used by NPL.

See:
- Want to learn python?: https://realpython.com/learning-paths
- Python language reference: https://realpython.com/ref
- Complete python tutorials: https://www.wscubetech.com/resources/python/libraries
- Libraries for data science: https://www.datacamp.com/blog/top-python-libraries-for-data-science


## Data Structure
REF: https://builtin.com/data-science/python-data-structures

A data structure is a way to organize data in computer memory so it can be easily accessed and used by computer programs. Every data structure has a specific format for organizing, processing, retrieving and storing data, allowing data to be manipulated in various ways by users and computer systems. Data structures are fundamental to modern software and programming languages. They can be built-in or user-defined, and range from basic to advanced types.

1. The four main types of built-in Python data structures are
- lists
- tuples
- sets
- dictionaries
  
2. Users can also implement custom structures like stacks, queues and trees for more complex data manipulation.
- stacks: see the end of this doc
- queues: 


## Sequence

A sequence is a data type that adheres to the "sequence protocol", meaning its elements are ordered and can be accessed using an integer index (including negative indices for counting from the end) and slicing. Common operations applicable to all sequences include: 
- Indexing: Accessing individual elements (e.g., my_sequence[0]).
- Slicing: Extracting a portion of the sequence (e.g., my_sequence[1:3]).
- Length: Using the len() function.
- Iteration: Looping through elements in order.
- Membership testing: Using the in and not in operators. 

Examples of built-in Python sequence types are: 
- list
- tuple
- str (strings)
- range (a function to generate a range of sequence which can used to form a list or a loop)
- bytes and bytearray

Non built-in Python sequence types are: 
- array
- numpy.narray
  
Key Comparison on List, Array and numpy.narray 

|Feature| Python List| Python Array (array module)| NumPy Array (numpy.ndarray)|
|-------|  ----------|  --------------------------|  --------------------------|
|Data Types|	Heterogeneous (mixed types)| Homogeneous (single type)| Homogeneous (single type)|
|Setup| Built-in (no import needed)| Must import array| Must import numpy|
|Memory| Higher (stores references)| Lower (compact storage)| Very low (highly optimized)|
|Math Ops| Limited (no vectorization)| Basic operations only| Powerful (vectorized)|


## List

In [1]:
my_list = ['apple', 'banana', 'cherry']
for item in my_list:
    print(f"Item: {item}")

Item: apple
Item: banana
Item: cherry


In [2]:
# accessing elements using square brackets [n] or [n:m] or [-n] (from last element)
my_list = ['apple', 'banana', 'cherry']
print(f"list: {my_list}")
print(f"list[0]: {my_list[0]}")   # First element, retunring an item
print(f"list[-1]: {my_list[-1]}")  # Last element
print(f"list[0:2]: {my_list[0:2]}") # Slicing, returning a list
my_list.append("orange")
print(f"list: {my_list}")


list: ['apple', 'banana', 'cherry']
list[0]: apple
list[-1]: cherry
list[0:2]: ['apple', 'banana']
list: ['apple', 'banana', 'cherry', 'orange']


## Tuple
In Python, a tuple is an ordered, immutable sequence of elements. This means that once a tuple is created, its contents cannot be changed (elements cannot be added, removed, or modified). Tuples are defined by enclosing comma-separated values within parentheses ().

See: https://www.geeksforgeeks.org/python/python-difference-between-list-and-tuple/

Key Differences

|Feature| 	      List|	                           Tuple|
|-------|         ----|                            -----| 
|Mutability|      Mutable (can be modified)|	   Immutable (cannot be modified)|
|Syntax|	      Uses square brackets []| 	       Uses parentheses ()|
|Size|	          Dynamic size (can grow/shrink)|  Fixed size after creation|
|Performance|	  Slightly slower|	               Generally faster|
|Memory|	      Consumes more (over-allocates)|  Consumes less (fixed size)|
|Methods|	      Many built-in methods (e.g., append, insert, remove, sort)|           Fewer methods (e.g., count, index)]|
|Dictionary Keys| Cannot be used as dictionary keys (unhashable)|  Can be used as dictionary keys (hashable if contents are hashable)|
|Typical Use|	  Homogeneous data (items of same type), dynamic collections|	Heterogeneous data (items of different types), fixed records, function return values|


In [3]:
# Empty tuple
empty_tuple = ()

# Tuple with multiple elements
my_tuple = (1, "hello", 3.14, True)
print(f"tuple: {my_tuple}")

# Tuple with a single element (note the comma)
single_element_tuple = ("apple",)
print(single_element_tuple)
print(f"single element tuple: {single_element_tuple}")

# Tuple without parentheses (comma-separated values)
another_tuple = 10, 20, 30
print(f"another tuple: {another_tuple}")


tuple: (1, 'hello', 3.14, True)
('apple',)
single element tuple: ('apple',)
another tuple: (10, 20, 30)


In [32]:
# Accessging tuples
my_tuple = (1, "hello", 3.14, True)
print(f"tuple: {my_tuple}")

# Accessing by positive index
print(f"my_tuple[0]: {my_tuple[0]}")     # First element
print(f"my_tuple[1]: {my_tuple[1]}")     # Second element

# Accessing by negative index
print(f"my_tuple[-1]: {my_tuple[-1]}")   # Last element

# Slicing
print(f"my_tuple[1:3]: {my_tuple[1:3]}") # Slicing


tuple: (1, 'hello', 3.14, True)
my_tuple[0]: 1
my_tuple[1]: hello
my_tuple[-1]: True
my_tuple[1:3]: ('hello', 3.14)


## Range function

The range() function in Python is used to generate a sequence of integers within a specified range. It is most commonly used in loops to control how many times a block of code runs.

Syntax: range(start, stop, step)
Default: start = 0, step = 1
Valid values: start, stop and step can be negative or positive.

In [25]:
# Default start and step
for i in range(2):
    print(i, end=" ")
print()

# start, stop and step can be negative
for i in range(-3,-5,-1):
    print(i, end=" ")
print()

# Using range in List Comprehension
list1 = [x for x in range(10) if x % 2 == 0]
print(list1)

0 1 
-3 -4 
[0, 2, 4, 6, 8]


## Array

In [27]:
import array

# Create an array of signed integers ('i')
numbers = array.array('i', [10, 20, 30, 40])
print(numbers)

# Access and modify
print(numbers[2])  # Output: 30
numbers[0] = 15

# Basic operations
numbers.append(50)
numbers.reverse()
print(numbers)

array('i', [10, 20, 30, 40])
30
array('i', [50, 40, 30, 20, 15])


## nummp array

In [30]:
import numpy as np

# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Perform element-wise math (cannot be done easily with standard lists)
print(arr * 2)  # Output: [ 2  4  6  8 10]

# Create a 2D array (Matrix)
matrix = np.array([[1, 2], [3, 4]])
print(matrix.shape)  # Output: (2, 2)

[ 2  4  6  8 10]
(2, 2)


## Dictionary (Map)

In [13]:
my_dict = {'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}

# Enumerate through the dictionary's items()
for index, (key, value) in enumerate(my_dict.items()):
    print(f"Index: {index}, Key: {key}, Value: {value}")

Index: 0, Key: apple, Value: 1
Index: 1, Key: banana, Value: 2
Index: 2, Key: cherry, Value: 3
Index: 3, Key: date, Value: 4


In [12]:
# accessing elements using square brackets ["key"] or .get function
my_dict = {'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}
print(f"Value: {my_dict['apple']}")
print(f"Value: {my_dict.get('banana')}")

Value: 1
Value: 2


## Array (numpy n-dimentional array)

N-dimensional array.

References: 
1. https://numpy.org/doc/stable/reference/arrays.ndarray.html
2. google: numpy array tutorial python


In [7]:
import pandas as pd
import numpy as np

# Syntax for creating an array
# np.ndarray(shape, dtype=float, buffer=None, offset=0, strides=None, order=None)
# np.ndarray(n, dtype)     # create one dim array of n elements with value=0
# np.ndarray((n,m), dtype) # create NxM 2-dim array with value=0
# np.array(list)           # create one dim from a list
# np.aray(list1, list2)    # create 2 dim array from 2 list
# RANDOM array: see next cell

array = np.ndarray(5, dtype=int)
array = np.ndarray(5, dtype=float)
array = np.ndarray(5) # default dtype=float

print("Array value: ")
print(array)
print("Array type: ", type(array))
print("Array std():", array.std())

list = [1, 2, 3]
array = np.array(list)
print("Array value: ")
print(array)

nested_list = [[1, 2, 3], [4, 5, 6]]
matrix = np.array(nested_list)
print("Matrix value: ")
print(matrix)
print("Matrix type: ", type(matrix))
print("Matrix std(): ", matrix.std())
print("Matrix [0,1]: ", matrix[0, 1])   # Access element at row 0, column 1
print("Matrix [:,1]: ",  matrix[:, 1])  # Access all elements in column 1


Array value: 
[ 1.    2.75  6.   10.75 17.  ]
Array type:  <class 'numpy.ndarray'>
Array std(): 5.7943938423272545
Array value: 
[1 2 3]
Matrix value: 
[[1 2 3]
 [4 5 6]]
Matrix type:  <class 'numpy.ndarray'>
Matrix std():  1.707825127659933
Matrix [0,1]:  2
Matrix [:,1]:  [2 5]


## Vector (numpy n-dimentional array)

In Python, vectors are primarily implemented using the numpy library as one-dimensional arrays (ndarray). 
Standard Python lists can also store elements but are not optimized for mathematical vector operations like numpy arrays.

REF: https://codesignal.com/learn/courses/vector-and-matrix-operations-with-numpy

In [8]:
import numpy as np

# Create a simple vector
vector_a = np.array([1, 2, 3])
print(vector_a)

# Create a vector with specific data types (e.g., floats)
vector_b = np.array([1.0, 2.5, 3.2])
print(vector_b)

[1 2 3]
[1.  2.5 3.2]


In [11]:
# Addition: each element of vector_a is added to the corresponding element of vector_b,
vector_c = vector_a + vector_b
print("Vector addition:", vector_c)

Vector addition: [2.  4.5 6.2]


## Enumeration on List

The enumerate() function in Python is a built-in function that adds a counter to an iterable object and returns an enumerate object. This object yields pairs of (index, value) for each item in the iterable, making it convenient to access both the position and the element during iteration.


In [6]:
my_list = ['apple', 'banana', 'cherry']
for item in my_list:
    print(f"item: {item}")

item: apple
item: banana
item: cherry


In [19]:
my_list = ['apple', 'banana', 'cherry']
for item in enumerate(my_list):
    print(f"item: {item}")

item: (0, 'apple')
item: (1, 'banana')
item: (2, 'cherry')


In [7]:
my_list = ['apple', 'banana', 'cherry']
for index, item in enumerate(my_list):
    print(f"Index: {index}, Item: {item}")


Index: 0, Item: apple
Index: 1, Item: banana
Index: 2, Item: cherry


## Enumeration on dictionary

The enumerate() function in Python can be effectively used with dictionaries to iterate through their items (key-value pairs) while simultaneously obtaining an index for each item. This is particularly useful when you need to track the position of items during iteration.

In [16]:
my_dict = {'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}

# Enumerate through the dictionary's items()
for index, (key, value) in enumerate(my_dict.items()):
    print(f"Index: {index}, Key: {key}, Value: {value}")

my_dict data type: <class 'dict'>
Index: 0, Key: apple, Value: 1
Index: 1, Key: banana, Value: 2
Index: 2, Key: cherry, Value: 3
Index: 3, Key: date, Value: 4


In [2]:
my_dict = {'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}

# Enumerate through the dictionary's keys()
for index, key in enumerate(my_dict.keys()):
    print(f"Index: {index}, Key: {key}")

Index: 0, Key: apple
Index: 1, Key: banana
Index: 2, Key: cherry
Index: 3, Key: date


In [3]:
my_dict = {'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}

# Enumerate through the dictionary's values()
for index, value in enumerate(my_dict.values()):
    print(f"Index: {index}, Value: {value}")

Index: 0, Value: 1
Index: 1, Value: 2
Index: 2, Value: 3
Index: 3, Value: 4


## The map() function

The Python map() function applies a given function to each item of an iterable (like a list, tuple, or set).
It returns a map object (an iterator) containing the results. 
This allows for efficient data transformation without using explicit loops.  

Syntax: map(function, iterable, ...)
* function: The function to execute for each item.  The function can be a lambda.
* iterable: One or more sequence, collection, or iterator objects. The function must accept as many arguments as there are iterables.
* Return: In Python 3, map() returns a lazy iterator (a map object) that yields results on demand, which is memory efficient for large datasets. To see the results immediately as a list, you must convert the map object using list() or a star operator (unpack operator)


In [17]:
# Example using tradictional function
def square(number):
  return number ** 2

numbers = [1, 2, 3, 4, 5]
squared_numbers_map = map(square, numbers)
print(f"map function returns type: {type(squared_numbers_map)}")

# Convert the map object to a list to view results
# squared_numbers_list = list(squared_numbers_map) # runtime error: 'list' object is not callable
squared_numbers_list = [*squared_numbers_map]
print(squared_numbers_list)

map function returns type: <class 'map'>
[1, 4, 9, 16, 25]


In [46]:
# Example using lambda

celsius_temps = [0.0, 10.0, 20.0, 30.0, 40.0]
# Convert to Fahrenheit: (temp * 9/5) + 32
fahrenheit_temps = [*(map(lambda temp: (temp * 9/5) + 32, celsius_temps))] # Create a list after * which unpacking the iterator
print(fahrenheit_temps)

[32.0, 50.0, 68.0, 86.0, 104.0]


In [40]:
en_stopwords = ['a', 'the']
text_list = ["a is good", "b is the mean"]
text_map = map(lambda x: ' '.join([word for word in x.split() if word not in (en_stopwords)]), text_list)
clean_text_list = [*text_map]
print (clean_text_list)

['is good', 'b is mean']


## List iteration (list.apply()).  See my ListComprehension module

Methods to Apply a Function to a List

|Method 	|Description     |Best For|
|------     |-----------     |--------|
|List Comprehension	  |Creates a new list by applying an expression/function to each item in an existing list. Often considered the most "Pythonic" and readable way for simple operations.	|Simple transformations, general use, compatibility across Python 2 and 3.|
|map() function	    |Applies a given function to each item of an iterable (like a list) and returns a lazy iterator (which needs to be converted to a list using list() in Python 3). |When you already have a function defined, or for performance with very large lists (due to lazy evaluation).|
|for loop   |The traditional, explicit way to iterate through each element and perform an operation, usually appending the results to a new list or modifying in-place.   |Complex logic, conditional operations, or when in-place modification is required.|
|NumPy/Pandas|	Libraries optimized for numerical operations and data processing on large datasets, offering vectorized operations.	|Efficient processing of large numerical arrays or structured data.|


In [27]:
# Sample of list comprehension
my_list = ['a', 'b', 3, 4]
print([x.upper() for x in my_list if isinstance(x, (str))])
print([x * 2 for x in my_list if isinstance(x, (int, float))])


['A', 'B']
[6, 8]


## Queue
REF: https://realpython.com/ref/stdlib/queue/

Python provides several built-in ways to implement queues, each suited for different use cases.

Queues are linear data structures used to manage data or tasks in a "First In, First Out" (FIFO) manner, ensuring the first element added is the first one removed. They act as buffers to hold data for later processing, manage asynchronous communication between systems, and handle task scheduling to optimize resource usage. 

Common Uses of Queues:
- Operating Systems and Task Scheduling: Used for CPU scheduling, job scheduling for printers, and managing I/O requests where tasks wait to be processed.
- Asynchronous Processing (Message Queues): Used in software architecture to decouple services, allowing a system to handle traffic spikes, manage background tasks, and process tasks "fire-and-forget" style.
- Data Structures and Algorithms: Implemented for breadth-first search (BFS) on graphs and managing queues for undo functionality in applications.
- Real-world Modeling: Applied in scenarios requiring ordered servicing, such as call center, call handling, and customer ticketing systems.

Examples of Queue Use Cases:
- Web Servers: Handling incoming requests in order.
- Print Spooling: Managing documents sent to a printer in the order they were submitted.
- Data Buffering: Handling data streaming or high-volume data transfers.
- Message Queues: Technologies like RabbitMQ or Kafka used for service communication.


In [38]:
# Using the queue Module (for Threading) 

import queue

# Create a thread-safe queue with a maximum size of 3
q = queue.Queue(maxsize=3)

# Add items using put()
q.put('Task A')
q.put('Task B')
q.put('Task C')

# Remove items using get()
item1 = q.get()
item2 = q.get()

print(f"Processed {item1}")
print(f"Processed {item2}")
print(f"Queue size after getting items: {q.qsize()}")


Processed Task A
Processed Task B
Queue size after getting items: 1


In [40]:
# Basic Usage with collections.deque for typical single-threaded use.
from collections import deque

# Create a queue
my_queue = deque()

# Add items (enqueue)
my_queue.append('Task 1')
my_queue.append('Task 2')
my_queue.append('Task 3')

print(f"Current queue: {list(my_queue)}")  # create a list from a queue

# Remove items (dequeue)
first_item = my_queue.popleft()
second_item = my_queue.popleft()

print(f"Removed item: {first_item}")
print(f"Removed item: {second_item}")
print(f"Remaining queue: {list(my_queue)}")


Current queue: ['Task 1', 'Task 2', 'Task 3']
Removed item: Task 1
Removed item: Task 2
Remaining queue: ['Task 3']


## Stack

A stack is a linear data structure that operates on the Last-In, First-Out (LIFO) principle, meaning the most recently added element is the first one to be removed. Stacks are essential in computer science for managing data that needs to be accessed in reverse order, such as tracking recent actions, managing function calls, or parsing nested structures. 

Here are the primary uses of stacks:
1. Function Call Management (Call Stack) 
- Recursion: When a function calls itself, the system uses a stack to store a "snapshot" of each call, including local variables, so it can return to the correct place when the function finishes.
- Procedure Calls: In programming, when one function calls another, the current execution state is "pushed" onto the stack; when the function finishes, it is "popped" to return control to the caller. 

2. "Undo" Mechanisms in Applications
- Undo/Redo: Text editors (like Notepad), graphic editors (like Photoshop), and browsers use a stack to track actions. The last action performed is pushed onto the stack. When you hit "Undo," that last action is popped and reversed.
- Browser History: Every URL you visit is pushed onto a stack. Clicking the "Back" button pops the most recent page to take you to the previous one. 

3. Syntax Parsing and Validation
- Balanced Brackets: Compilers and IDEs use stacks to verify if code is correctly formed by matching opening symbols (e.g., (, [, {) with corresponding closing symbols (e.g., ), ], }).
- Expression Evaluation: Calculators use stacks to handle operator precedence (order of operations) and convert infix expressions (e.g., 2+3) to postfix or prefix notation. 

4. Backtracking Algorithms
- Maze Solving & Graph Traversal: When searching for a path, you can use a stack to push the current path. If you hit a dead end, you can pop from the stack to "backtrack" to the last known correct point.
- Depth-First Search (DFS): Algorithms that traverse trees or graphs, such as finding a path in a maze, use a stack to remember which node to visit next. 

5. Memory Management
- Automatic Variable Allocation: A specific region of RAM, known as the "stack," is used for fast, automatic allocation and deallocation of memory for local variables within functions.

In [33]:
# Implement a stack
class Stack:
    def __init__(self):
        self._items = []

    def push(self, item):
        self._items.append(item)

    def pop(self):
        if self.is_empty():
            raise IndexError("pop from empty stack")
        return self._items.pop()

    def peek(self):
        if self.is_empty():
            raise IndexError("peek from empty stack")
        return self._items[-1]

    def is_empty(self):
        return len(self._items) == 0

    def size(self):
        return len(self._items)


s = Stack()
s.push(10)
s.push(20)
print(s.pop())   # 20
print(s.peek())  # 10
print(s.size())


20
10
1


In [37]:
# Using Built-in List Directly (Quick & Pythonic)
# This is what most Python developers actually use
stack = []
stack.append(10)    # push
stack.append(20)

print(stack.pop())  # pop
print(len(stack))

20
1
